name: Build + Test Mac-Windows

on:
  push:
    tags:
      - "*" # Push events to every tag
    branches:
      - dev
      - master

jobs:
  run_build_tests:
    name: build_tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
      # Downgrade mingw due to a regression causing tests with --race enabled to
      # fail. See: https://github.com/actions/virtual-environments/issues/5841
      - name: Install mingw 10.2.0
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: Choco-Install -PackageName mingw -ArgumentList "--version", "10.2.0", "--allow-downgrade"
      - name: build_test
        shell: bash
        run: .github/workflows/build_and_test.sh
